#!/bin/bash
# eza_ls - A wrapper script that makes eza behave like ls (BSD and GNU compatible)

args=("$@")
eza_args=()
file_args=()
has_file_arg=0
has_reverse=0
has_sort=0
sort_type="none"
has_human_readable=0
has_group=0
print_only=0
needs_long=0
unsupported_flags=()

scan_arg() {
    local arg="$1"
    case "$arg" in
        -S|-t|-X)
            has_sort=1
            has_reverse=1
            ;;
        --sort=*)
            has_sort=1
            has_reverse=1
            ;;
        -f)
            has_sort=1
            ;;
        -h|--human-readable)
            has_human_readable=1
            ;;
        -G|--no-group)
            has_group=1
            ;;
        -g|-o)
            has_group=1
            needs_long=1
            ;;
        -l)
            needs_long=1
            ;;
        --full-time)
            needs_long=1
            ;;
        --eza)
            print_only=1
            ;;
    esac
}

arg_index=0
seen_ddash=0
while [[ $arg_index -lt ${#args[@]} ]]; do
    arg="${args[$arg_index]}"

    if [[ "$arg" == "--" ]]; then
        seen_ddash=1
        ((arg_index++))
        continue
    fi

    if [[ $seen_ddash -eq 0 && "$arg" == -* && "${#arg}" -gt 1 && "$arg" != "--"* ]]; then
        for ((i=1; i<${#arg}; i++)); do
            scan_arg "-${arg:$i:1}"
        done
    elif [[ $seen_ddash -eq 0 ]]; then
        scan_arg "$arg"
    fi

    case "$arg" in
        -b|-I|-w|--block-size|-D|--ignore|--width)
            ((arg_index++))
            ;;
    esac

    ((arg_index++))
done

process_arg() {
    local arg="$1"

    case "$arg" in
        # extended
        -@)
            eza_args+=("--extended")
            ;;
        # one_per_line
        -1)
            eza_args+=("--oneline")
            ;;
        # show_hidden
        -a|--all)
            eza_args+=("--all" "--all")
            ;;
        # almost_all
        -A)
            eza_args+=("--almost-all")
            ;;
        # author
        --author)
            unsupported_flags+=("$arg")
            ;;
        # escape
        -b)
            unsupported_flags+=("$arg")
            ;;
        # blocksize
        --block-size=*)
            size="${arg#*=}"
            case "$size" in
                K) eza_args+=("--binary") ;;
                B) eza_args+=("--bytes") ;;
                *) unsupported_flags+=("$arg") ;;
            esac
            ;;
        # ignore_backups
        -B|--ignore-backups)
            eza_args+=("--ignore-glob=*~")
            ;;
        # ctime_sort
        -c)
            eza_args+=("--time=changed" "--time-style=long-iso")
            ;;
        # columns
        -C)
            eza_args+=("--grid")
            ;;
        # dirs_files
        -d|--directory)
            eza_args+=("--treat-dirs-as-files")
            ;;
        # date_format
        -D)
            ((arg_index++))
            eza_args+=("--time-style=+${args[$arg_index]}")
            ;;
        # show_acl
        -e)
            unsupported_flags+=("$arg")
            ;;
        # no_sort
        -f)
            eza_args+=("--all")
            eza_args+=("--all")
            sort_type="none"
            ;;
        # classify
        -F|--classify|--classify=*)
            if [[ "$arg" == *=* ]]; then
                classify="${arg#*=}"
                case "$classify" in
                    always|auto|never) eza_args+=("--classify=$classify") ;;
                    *) unsupported_flags+=("$arg") ;;
                esac
            else
                eza_args+=("--classify=auto")
            fi
            ;;
        # no_group
        -G|--no-group)
            # Handled by has_group
            ;;
        # human
        -h|--human-readable)
            # Handled by has_human_readable
            ;;
        # follow_symlinks
        -H)
            eza_args+=("--links")
            ;;
        # inode
        -i|--inode)
            eza_args+=("--inode")
            ;;
        # ignore_pattern
        -I|--ignore)
            if [[ "$arg" == *=* ]]; then
                eza_args+=("--ignore-glob=${arg#*=}")
            else
                ((arg_index++))
                eza_args+=("--ignore-glob=${args[$arg_index]}")
            fi
            ;;
        # kibibytes
        -k|--kibibytes)
            eza_args+=("--binary")
            ;;
        # long_format
        -l)
            # Handled by needs_long
            ;;
        # comma_list
        -m)
            unsupported_flags+=("$arg")
            ;;
        # numericid
        -n|--numeric-uid-gid)
            eza_args+=("--numeric")
            ;;
        # file_flags
        -O)
            unsupported_flags+=("$arg")
            ;;
        # no_owner
        -g)
            eza_args+=("--no-user")
            eza_args+=("--group")
            ;;
        # no_group
        -o)
            # Handled by has_group and needs_long
            ;;
        # no_symlinks
        -P)
            unsupported_flags+=("$arg")
            ;;
        # dir_slash
        -p)
            eza_args+=("--classify=auto")
            ;;
        # hide_control
        -q|--hide-control-chars|--show-control-chars|--format=*|--dereference-command-line-symlink-to-dir)
            unsupported_flags+=("$arg")
            ;;
        # reverse
        -r|--reverse)
            (( has_reverse = !has_reverse ))
            ;;
        # recursive
        -R|--recursive)
            eza_args+=("--recurse")
            ;;
        # size
        -s|--size)
            eza_args+=("--blocksize")
            ;;
        # si
        --si)
            unsupported_flags+=("$arg")
            ;;
        # sort_size
        -S)
            sort_type="size"
            ;;
        # sort_time
        -t)
            sort_type="modified"
            ;;
        # full_time
        -T)
            eza_args+=("--time-style=full-iso")
            ;;
        # tabsize
        --tab-size=*|--tabsize=*)
            unsupported_flags+=("$arg")
            ;;
        # access_time_sort
        -u)
            eza_args+=("--accessed")
            ;;
        # created_time
        -U)
            eza_args+=("--created")
            ;;
        # unedited / version_sort
        -v)
            unsupported_flags+=("$arg")
            ;;
        --version)
            eza_args+=("--version")
            ;;
        # whiteouts
        -W)
            unsupported_flags+=("$arg")
            ;;
        # width
        -w|--width)
            if [[ "$arg" == *=* ]]; then
                eza_args+=("--width=${arg#*=}")
            else
                ((arg_index++))
                eza_args+=("--width=${args[$arg_index]}")
            fi
            ;;
        # across
        -x)
            eza_args+=("--across")
            ;;
        # extension
        -X|--sort=extension)
            sort_type="extension"
            ;;
        # context
        -Z|--context)
            eza_args+=("--context")
            ;;
        # color
        --color|--color=*)
            if [[ "$arg" == *=* ]]; then
                color="${arg#*=}"
            else
                color="always"
            fi
            case "$color" in
                always) eza_args+=("--colour=always") ;;
                auto) eza_args+=("--colour=auto") ;;
                never) eza_args+=("--colour=never") ;;
                *) unsupported_flags+=("$arg") ;;
            esac
            ;;
        # dereference
        -L|--dereference|--dereference-command-line)
            eza_args+=("--dereference")
            ;;
        # dired
        --dired)
            unsupported_flags+=("$arg")
            ;;
        # filetype
        --file-type)
            eza_args+=("--classify=never")
            ;;
        # full_timestamp
        --full-time)
            eza_args+=("--time-style=full-iso")
            ;;
        # dirs_first
        --group-directories-first)
            eza_args+=("--group-directories-first")
            ;;
        # hide_pattern
        --hide=*)
            eza_args+=("--ignore-glob=${arg#*=}")
            ;;
        # hyperlink
        --hyperlink|--hyperlink=*)
            if [[ "$arg" == *=* ]]; then
                hyperlink="${arg#*=}"
                case "$hyperlink" in
                    always|auto) eza_args+=("--hyperlink") ;;
                    never) ;; # Do nothing
                    *) unsupported_flags+=("$arg") ;;
                esac
            else
                eza_args+=("--hyperlink")
            fi
            ;;
        # indicator
        --indicator-style=*)
            style="${arg#*=}"
            case "$style" in
                none) ;; # Do nothing
                file-type) eza_args+=("--classify=never") ;;
                classify) eza_args+=("--classify=always") ;;
                slash) eza_args+=("--classify=auto") ;;
                *) unsupported_flags+=("$arg") ;;
            esac
            ;;
        # quoting
        --quoting-style=*)
            unsupported_flags+=("$arg")
            ;;
        # nul_output
        --zero)
            unsupported_flags+=("$arg")
            ;;
        # no_quoting
        -N|--literal)
            eza_args+=("--no-quotes")
            ;;
        # quote_names
        -Q|--quote-name)
            unsupported_flags+=("$arg")
            ;;
        # sort_field
        --sort=*)
            sort_field="${arg#*=}"
            case "$sort_field" in
                none) sort_type="none" ;;
                time) sort_type="modified" ;;
                size) sort_type="size" ;;
                extension) sort_type="extension" ;;
                name) sort_type="name" ;;
                version) sort_type="name" ;;
                *) sort_type="$sort_field" ;;
            esac
            ;;
        # time_field
        --time=*)
            time_field="${arg#*=}"
            case "$time_field" in
                atime|access|use|accessed) eza_args+=("--accessed") ;;
                ctime|status|changed) eza_args+=("--changed") ;;
                birth|creation|created) eza_args+=("--created") ;;
                *) eza_args+=("--time=$time_field") ;;
            esac
            ;;
        # time_style
        --time-style=*)
            style="${arg#*=}"
            case "$style" in
                full-iso) eza_args+=("--time-style=full-iso") ;;
                long-iso) eza_args+=("--time-style=long-iso") ;;
                iso) eza_args+=("--time-style=iso") ;;
                +*) eza_args+=("--time-style=$style") ;;
                *) eza_args+=("--time-style=$style") ;;
            esac
            ;;
        # Debug: print eza command
        --eza)
            print_only=1
            ;;
        # Help: print help
        --help)
            awk '/^# HELP_START$/,/^# HELP_END$/' "$0" | sed '1d;$d'
            exit 0
            ;;
        # Debug: list unsupported options
        --unsupported)
            awk '/^# UNSUPPORTED_START$/,/^# UNSUPPORTED_END$/' "$0" | sed '1d;$d'
            exit 0
            ;;
        # Separator: pass through
        --)
            ;;
        # other
        -*)
            unsupported_flags+=("$arg")
            ;;
        # File argument
        *)
            eza_args+=("$arg")
            has_file_arg=1
            ;;
    esac
}

arg_index=0
stop_flag_processing=0
while [[ $arg_index -lt ${#args[@]} ]]; do
    arg="${args[$arg_index]}"
    consumed_args=0

    if [[ "$arg" == "--" ]]; then
        eza_args+=("--")
        stop_flag_processing=1
        ((arg_index++))
        continue
    fi

    if [[ $stop_flag_processing -eq 1 ]]; then
        eza_args+=("$arg")
        has_file_arg=1
    elif [[ "$arg" == -* && "${#arg}" -gt 1 && "$arg" != "--"* ]]; then
        for ((i=1; i<${#arg}; i++)); do
            process_arg "-${arg:$i:1}"
        done
    else
        process_arg "$arg"
        # check if arg consumes next
        case "$arg" in
            -I|-w|-D|--block-size|--ignore|--width)
                consumed_args=1
                ;;
        esac
    fi

    arg_index=$((arg_index + 1 + consumed_args))
done

if (( has_sort )); then
    eza_args+=("--sort=$sort_type")
fi

if (( has_reverse )); then
    eza_args+=("--reverse")
fi

if (( needs_long )); then
    eza_args+=("--long")
fi

if (( !has_file_arg )); then
    eza_args+=(".")
fi

if (( !has_human_readable )); then
    eza_args+=("--bytes")
fi

if (( !has_group )); then
    eza_args+=("-g")
fi

if [[ ${#unsupported_flags[@]} -gt 0 ]]; then
    echo "warning: unsupported option(s): ${unsupported_flags[*]}" >&2
fi

if ((print_only)); then
    echo "eza ${eza_args[*]}"
else
    exec eza "${eza_args[@]}"
fi

exit 0

# HELP_START
Usage: eza_ls [flags] [directory]

The better eza drop-in replacement for ls.

Flags:
  -1                    One entry per line
  -a, --all             Show hidden files
  -A, --almost-all      Show hidden files (no . or ..)
  -B, --ignore-backups  Ignore backup files (~)
  -c                    Use ctime for sorting
  -C                    List in columns
  -d, --directory       List directories as files
  -D format             Custom date format
  -f                    No sort, show all
  -F, --classify        Type indicators (*/=>@|)
  -g                    Long without owner
  -G, --no-group        No group column
  -h, --human-readable  Human readable sizes
  -H                    Follow symlinks on command line
  -i, --inode           Show inode numbers
  -I, --ignore PATTERN  Ignore pattern
  -k, --kibibytes       1024-byte blocks
  -l                    Long format
  -L, --dereference     Follow symlinks
  -n, --numeric-uid-gid Numeric UID/GID
  -N, --literal         No quoting
  -o                    Long without group
  -p, --indicator-style Indicator for directories
  -r, --reverse         Reverse sort
  -R, --recursive       Recursive
  -s, --size            Show size
  -S                    Sort by size (largest first)
  -t                    Sort by time
  -T                    Full timestamp
  -u                    Use access time
  -U                    Use created time
  -w, --width=COLS      Set output width
  -x                    Sort across columns
  -X, --sort=extension  Sort by extension
  -Z, --context         Security context
  -@                    Extended attributes

Long options:
  --color=WHEN          Color output (auto/always/never)
  --file-type           File type indicator (no *)
  --full-time           Full timestamp
  --group-directories-first
  --hide=PATTERN        Hide pattern
  --hyperlink[=WHEN]    Hyperlink files
  --indicator-style=WORD Indicator style
  --sort=WORD           Sort field
  --time=FIELD          Time field
  --time-style=STYLE    Time format
  --version             Output version information

Debug options:
  --eza                 Print eza command instead of executing
  --help                Show this help
  --unsupported         List unsupported options

Eza repository: https://github.com/eza-community/eza
# HELP_END

# UNSUPPORTED_START
Unsupported options in eza_ls:

BSD-specific (macOS):
  -e         Print ACL (use -Z for security context)
  -O         File flags
  -m         Comma-separated list
  -P         Don't follow symlinks
  -v         Force unedited printing
  -W         Display whiteouts

GNU-specific:
  --author                Print author
  -b, --escape            Escape non-printable (eza uses unicode)
  -D, --dired             generate output designed for Emacs' dired mode
  --dereference-command-line-symlink-to-dir
                          Follow command line symlinks to directories
  --format                Set output format
  -q, --hide-control-chars Print ? for nongraphic chars
  -Q, --quote-name        Quote names
  --quoting-style=WORD    Quoting style
  --show-control-chars    Show control characters
  --si                    SI units (powers of 1000)
  -T, --tabsize=COLS      Tab size
  -U                      Do not sort (eza always sorts)
  -v                      Version sort
  --zero                  End lines with NUL

Eza repository: https://github.com/eza-community/eza
# UNSUPPORTED_END
